-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 16, 2018 at 03:28 AM
-- Server version: 10.1.28-MariaDB
-- PHP Version: 7.1.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `pregnancy_project`
--

-- --------------------------------------------------------

--
-- Table structure for table `pregnancy_by_week`
--

CREATE TABLE `pregnancy_by_week` (
  `id` int(4) NOT NULL,
  `user_id` int(255) NOT NULL,
  `mumsdev` text NOT NULL,
  `babydev` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `pregnancy_by_week`
--

INSERT INTO `pregnancy_by_week` (`id`, `user_id`, `mumsdev`, `babydev`) VALUES
(1, 0, 'Week one and conception/ fertilization hasn\'t occurred yet. This means that there wont be any symptoms or development for this week. This is the time for preparing for pregnancy by helping your partner to stay active and eat healthier to encourage a quicker conception.', 'At this stage the baby is still an idea that mum and dad are hoping becomes a reality. In a few short weeks fertilization can occur and your baby will begin its growing process.'),
(2, 0, 'This week you and your partner have just conceived. Most women at this stage won\'t be aware that they are pregnant. If your partner has been monitoring her basal body temperature she might notice a slight spike in her temperature. Although it will not be outwardly apparent now, her body is beginning the necessary changes to carry your baby to term.', 'Congratulations! Even though you may not know it you are pregnant!!\r\nThe cells in the body have merged together forming a zygote, which begins developing rapidly over the week, before implanting itself into the uterine wall. Your little baby is now termed as a blastocyst and the areas that will eventually form the embryo, amniotic sac and the placenta are taking shape.'),
(3, 0, 'Your baby has now implanted into your partners uterine wall and will continue its growth over the next 37 weeks. Your partner is also beginning to produce the hormone HCG which will give the give that positive test result. Though your partner may not know at this stage that she is pregnant, she may also be experiencing bloating, cramping or mood swings, and these might be the first symptoms of pregnancy. Your partner may also notice some light spotting, which you can reassure her is likely due to implantation.', 'The cells that are forming your baby have been undergoing a lot of changes and has now developed into two distinct layers. These two layers will form all of your babies organs and body parts. This week may also be an exciting one as your pregnancy might now be detectable on a home pregnancy test. As well as that, it is fascinating to know that at this early stage your baby already has a genetically predetermined hair and eye colour.'),
(4, 0, 'Your partner might get the first notion that she is pregnant at this stage. It can be hard to tell the symptoms apart from regular period pains, but mum might notice bloating, nausea or mild cramping at this point. For most the nausea and vomiting is still to come. Your partner may notice some food aversions but this is a normal start to the roller coaster of pregnancy.', 'Your little one is now the size of a poppy seed. The placenta has also begun to form at this stage and will transport vital materials such as oxygen and food to your baby by the end of this week. The neural tube which will eventually become your babies brain and spinal cord is forming. Your baby also consists now of 3 \'germ\' layers. The endoderm becomes the lungs and most other organs, the mesoderm grows into the heart and skeleton and the ectoderm which makes up the nervous system.'),
(5, 0, 'This is the time when your partner will be missing their first period, and if it hasn\'t already kicked in, nausea may be just around the corner. You might be able to help your partner with the nausea by combating it with things like peppermint and ginger. \r\n\r\nYour partner may also be experiencing physical symptoms such as sore breasts and a more frequent urge to use the bathroom. You might want to support your partner by helping them eat a healthy diet and engage in some light physical activity. Your partner will also need to start taking prenatal vitamins to aid the development of the baby. The healthier the mum, the healthier the baby will grow.', 'Your baby is now resembling a tiny tadpole and is approximately the size of a black peppercorn. The neural tube has grown a tail at this stage, however don\'t worry, this will be long gone before the baby is born. \r\n\r\nMost of the babies development at this stage is occurring in the brain, but your baby is primarily made up of its heart. Its circulatory system is nearly ready to go already, and its heart is beginning to form separate chambers. If you were to have an ultrasound now you might even be lucky enough to detect the heartbeat. \r\n\r\nYour baby is growing rapidly and nearly doubling in size each week. Major organs such as the stomach and liver, as well as bodily systems like the nervous system and digestive system are steadily developing. '),
(6, 0, 'During the 6th week of pregnancy most mothers-to-be will experience nausea, which usually occurs in the morning. Your partner might want some space in the morning, or alternatively want your support during these phases of morning sickness. Though it is important to note that morning sickness is not exclusive to the mornings. To try and help your partner combat the morning sickness, you can advise that she cuts out greasy or spicy foods, stays hydrated by drinking plenty of water, and gets plenty of rest.\r\n\r\nAt this week of pregnancy your partner will also experience increased fatigue to the point where small tasks can be significantly more daunting. Your partner is producing more blood than usual resulting in lower blood sugars and lower blood pressure. \r\n\r\nYour partner might also be experiencing painful breasts. This tenderness she is feeling may last through the entire first trimester of the pregnancy as a result of the breasts continuously growing. \r\n\r\nSpotting or bleeding in early pregnancy can be very common, however if your partner experiences this then it is best to call your healthcare provider and have everything checked over, as this could be an indicator of a miscarriage or an ectopic pregnancy. ', 'Bump is now the size of a blueberry this week, and measures approximately a quarter of an inch long. Your baby has progressed rapidly from the bunch of cells it started out as, and now its eyes and and nose are beginning to form, though they appear as no more than dark spots. \r\n\r\nThe development of your little ones lower body currently lags behind that of the upper body. Your baby at this stage is mostly made up of its head. At this stage as well, your baby is starting to straighten out from its previously curled up position. \r\n\r\nThese weeks are the most vital for your little ones development. Folic acid and other prenatal vitamins and a healthy diet can prevent neural tube defects which is crucial at this point. '),
(7, 0, 'This could be a rough week for your partner in terms of symptoms. However, she may also be one of the lucky few to experience no symptoms. This is common, but if you have any concerns you can always check with your healthcare provider. \r\n\r\nNow may also be a good time to discuss with your partner about how involved in the appointments you wish to be. You might want to go to all appointments and classes, or you may want to be present for just the big appointments like the 3 month scan. \r\n\r\nYour partner most notably will experience an increased frequency in trips to the bathroom. This is due to the uterus growing and the resulting pressure of this. Unfortunately, this is a symptom she is unlikely to see subside until after the birth or your baby. You or your partner might have also noticed an increase in the size of the breasts at this stage, and you partner may be feeling some discomfort with this. You can suggest the likes of a maternity bra to help ease this discomfort if she hasn\'t already got one.\r\n\r\nFood aversions and cravings will be more common at this stage so be careful about what food you cook or eat around your partner, as it may cause her to feel or be sick. This is a result of all the hormones that are coursing through the body at this stage. These hormones can also cause an increase in acne as well as the production of extra saliva. ', 'Your baby this week is similar in size to a little raspberry, and its brain is growing at the rate of approximately 100 cells every minute. That\'s a lot! Your baby is now over half an inch long. \r\n\r\nYour baby is starting to become more complex and human-like by this week. The heart and the kidneys are both starting development this week, as well as the beginnings of teeth and little buds on the end of the arm buds that will eventually form your little ones hands. \r\n\r\nThe beginnings of legs and toes are now starting to form on the little tail that your baby currently has. The head is still the most prominent part of development however, the tongue, ears and eyes are beginning to develop and it\'s little bones are starting to harden as well. '),
(8, 0, 'This week you or your partner might begin to notice a little bump in her midsection, unfortunately, at this early stage this is more likely to be water retention or bloating than the baby, as the uterus wouldn\'t have started growing outwards yet. \r\n\r\nCravings and aversions will be in full swing by now. It is not 100% certain what causes these symptoms, though it is considered to be a result of hormones. It is important to remind your partner that despite any cravings she may have, the healthier she eats the healthier the baby will be throughout the pregnancy. \r\n\r\nOne theory regarding cravings is that it is natures way of telling what nutrients the body and baby are in need of. Though it is unlikely that this is cause of cravings, and it is more likely caused by the heightened sense of smell. \r\n\r\nThis week you might see a decline in your partners mood swings (Yay! I hear you say). This is because the placenta has started to take over providing food and oxygen to the baby. This allows the hormones in your partners body to take a break. Your partner might be experiencing a heightened sense of smell as well as weird and vivid dreams and nausea. If your partner is experiencing bad nausea you could advise she try sucking on a ginger lollipop, or taking a chew-able form of prenatal vitamin. Cutting down on portions sizes to eat smaller amounts more frequently can also help reduce the feeling of nausea. If your partner hasn\'t experienced any morning sickness by this week, chances are she is one of the lucky few who won\'t experience this. ', 'This week marks the last few days of your baby being an embryo. Once this occurs it means that the tiny organs that it does have at this stage are almost ready to start functioning on their own. \r\n\r\nYour little one at this stage has little webbed fingers and toes and its limbs are growing rapidly everyday to form its arms and legs. Your baby in this week is roughly the size of a strawberry and should be moving around excessively, although you wont be able to feel anything for a while yet. '),
(9, 0, 'This week marks the start of the third month, and the last month within that dreaded first trimester. Once the 12 week mark has been reached, the chances of miscarriage are greatly decreased, but you are almost there so hang in a little while longer.\r\n\r\nThis week mum might be feeling moody and irritable and although these feelings normally leave by week 10, they return full force at the end of the pregnancy, so you have not seen the end of her irritability just yet. You might also notice that mum is extremely tired as well, this is very common at this stage. \r\n\r\nYour partner wont won\'t be showing yet, but if you feel her stomach, you will notice that it is a lot firmer than usual, and by now the uterus has doubled in size so a baby bump wont be far behind. It is common for a mum to gain between 1 and 5 pounds in their first trimester, however due to the food aversions and morning sickness it is also possible to lose weight instead.', 'Your little one is roughly an inch long and estimated to be the size of a pecan. Their essential muscles and body parts are all present now, though there is a long way to go before they will be fully formed. The kidneys, liver, brain and lungs are beginning to function on their own, but maybe more interestingly, this week marks the start of your baby developing its taste buds!\r\n\r\nAt this early stage you might be surprised to learn that the baby\'s eyesight is nearly fully developed already, however the eyes will fuse themselves shut until much later on in the pregnancy. This week, the inner ear has started to develop the fluid that will later allow your little one to have a sense of balance. One of the most exciting parts of week 9 is the increased likelihood that you might be able to hear your little bundle\'s heartbeat with the use of a fetal doppler. These are mainly used by hospital staff to listen to the baby\'s heartbeat, but they are also available online for purchase also.'),
(10, 0, 'By this week the mother should notice most of the symptoms she had start to subside. She should be settling into pregnancy better by now. \r\n\r\nShe might experience an increase in discharge this week as well as more visible veins due to the increased blood flow around the body. It is interesting to note that the blood flow increases between 30% and 50% during pregnancy. The increased discharge is also totally normal, however if there is any colour or odor to the discharge then you might suggest that she consults a healthcare provider as this can symbolize an infection. ', 'Week 10 and the baby is now roughly the size of a kumquat, measuring about 1 and a quarter inches long. If your baby is a boy his testes at this week are starting to produce testosterone. \r\n\r\nThe baby\'s heart rate beats at a super fast speed that is about twice as fast as your own. They are also moving around enough that if you were to have an ultrasound you would be able to witness these movements. '),
(11, 0, 'Most of the first trimester symptoms should be subsiding by now, however keep an eye out for excessive vomiting as it can cause dehydration and may need medical attention. \r\n\r\nThis week the baby\'s mum should begin feeling better. The second trimester ahead is one of the nicer trimesters, with minimal symptoms to endure. The placenta has taken over from much of what the mum\'s body was doing for the baby in the first few weeks of pregnancy. It is this transition that allows the symptoms to ease up, resulting in the mother feeling better in the weeks to come. This week might be the week you notice the development of linea nigra. This is a dark line that runs vertically from the pelvis to the belly button and sometimes above the belly button. It is completely harmless. If you believe in old wives tales, there are some that say the position of linea nigra if you have any can predict the gender of the baby. Worth reading into for fun if nothing else. ', 'This week your baby has officially graduated from being an embryo to a being a fetus! This is quite the milestone.\r\n\r\nIf your baby is a girl her ovaries are starting to develop underneath her thin skin, and the fingernails are also starting to make an appearance this week. The webbing that was previously between the baby\'s fingers and toes is now disappearing, and the baby is enjoying exploring its surroundings including its face. All this movement helps your baby to develop its co-ordination, though neither you nor the mother will be able to feel this movement just yet. \r\n\r\nThis week your baby measures 1 and a half inches long and is similar in size to a brussel sprout. Enjoy this time as they don\'t stay small for long.'),
(12, 0, 'This week is the last week of the first trimester, and it symbolizes the decrease in the odds of having a miscarriage. It is normally this week when people tell family and friends about the pregnancy due to the fact they have reached what is considered to be a much more stable stage of the pregnancy. Though it is important to note that miscarriages are possible at any time, for any reason, and passing this week does not mean that a miscarriage isn\'t possible anymore.\r\n\r\nMum might notice the onset of heartburn this week as the stomach struggles to breakdown grease and fatty foods. Heartburn is a pesky symptom that can be very bothersome for the mother. Rennies are heartburn tablets that are safe to ingest during pregnancy or while breastfeeding. If you are ever unsure if a product is safe during pregnancy read the labels and seek medical advice before consuming.\r\n\r\nThe uterus is now close in size to a baseball and can push on the stomach making heartburn worse. Try provide fresh fruit and vegetables for mum to eat as well as advise she eats smaller meals at a slower pace, and drinks lots of water. Other symptoms of this week might include headaches, heightened sense of smell, increase in gas and excess saliva. Each woman will experience different symptoms so it is hard to note everything that might occur this week.', 'This week you baby will start to develop its reflexes. How incredible! The baby is even starting to curl its little fingers and toes. At this stage if you were able to see through to the baby, you would notice it has the ability to wriggle in response to nudges or pokes from the outside, and this is due to the development of the baby\'s nerve endings. Unfortunately, it will still be a while before any of these movements can be felt by you, and possibly longer if the placenta in in front of the baby. \r\n\r\nThis week the baby begins to practice breathing by inhaling and exhaling the amniotic fluid. This not only prepares them for breathing but helps the development of their digestive system. Everything the baby swallows will eventually be passed out in its urine and the cycle continues. If the baby inhales the fluid too fast in can result in the baby having hiccups. When this can be felt it will resemble a rhythmic pulse in the same spot. \r\n\r\nThe kidneys are also beginning to function and the baby will be storing up waste that will form its first poo. It will be a tarry substance, often black in colour, which is known officially as meconium. This week your baby measures over 2 inches long which is a great growth spurt, and is roughly the size of an apricot. '),
(13, 0, 'Congratulations, you and your partner has officially reached the end of the first trimester by now. Most women find the first trimester to be the most difficult so thankfully the second trimester brings relief from those horrible symptoms such as morning sickness and fatigue. One prevalent symptom your partner might notice starting from week 13 is an increased sex drive. This is totally normal, healthy and safe up until your partner\'s water breaks. Second trimester symptoms include food cravings and aversions, swollen or tender breasts and constipation. \r\n\r\nYour partner may also be experiencing an increase in leukorrhea which is a milky vaginal discharge which is created by the body to protect the birth canal during pregnancy. This increase is nothing to worry about however you might suggest to your partner that the use of panty liners can help increase her comfort during this stage. ', 'You may be amazed to discover that at this early stage your baby already has fingerprints. It\'s own unique identity. Your baby\'s lower body development is also beginning to catch up with her upper body\'s development.\r\nYour baby\'s vocal cords are also developing and your little one will soon be covered in tiny little hairs known as lanugo. This occurs in order to help insulate your baby and keep them warm while they lack body fat as well as keeping the white substance called vernix in place in order to protect your baby\'s skin from drying out. \r\nThese small hairs are usually gone by the time your little one is born, however it is possible for some to remain especially if your child is premature.'),
(14, 0, 'Most women report that the second trimester is the most enjoyable. Your partner will notice a decrease in symptoms such as morning sickness and fatigue giving them a bit more energy than usual. Tell them to enjoy this stage as the third trimester will leave them feeling very big and uncomfortable, while they need to pee all the time. \r\n\r\nThe second trimester isn\'t all wonderful however, as your partner may experience headaches, an increased need to pee and dizziness, as well a some pain known as round ligament pain which is caused by the growing womb putting strain and pressure on the surrounding ligaments causing them to stretch. This is a common pain that will go away with rest. If however your partner is feeling an intense pain in their abdomen that doesn\'t go away with rest, then seek out medical help from a healthcare provider.', 'Your baby\'s immune system is developing well however, it will take months or even years after your baby has been born before it is fully developed. \r\nYour baby is also moving around non-stop but you and your partner wont be able to feel these movements yet. At this stage you baby can even squint and suck it\'s thumb. Your little one is now approximately 3 and half inches long, which is similar in size to a beet, and your baby\'s weight will have doubled in size since last week. '),
(15, 0, 'At this stage your partner might actively be putting on weight so don\'t forget to tell her she is looking well as she might be noticing the weight she is putting on. \r\nShe only has more weight to come, so she might want to start preparing her wardrobe with some maternity wear.\r\n\r\nA stuffy nose can be a common symptom in the second trimester, along with other flu-like symptoms. Your partner might be noticing her skin starting to \'glow\' or she might have a break out with acne. Everyone\'s body reacts different to pregnancy. \r\nNext week is one for your partner to look forward to as they might be able to start feeling small movements however, it can take up to week 20 or so before they feel any movement, so don\'t panic if your partner doesn\'t notice movements by the following week.', 'Your baby is doing a good job of mimicking breathing at this stage. They are breathing in the amniotic fluid and that helps his lungs develop the air sacs they need for breathing when they are born.\r\nYour baby\'s heart can now pump 25 quarts of blood a day! That\'s a great development for your little one\'s heart. \r\nYour little one can also bend their elbows and knees and they might even be starting to grow some of their hair.\r\nYour baby is now approximately 4 inches long and is roughly the size of an avocado.'),
(16, 0, 'Your partner will probably spend a lot of time this week looking out for small movements that might be the baby moving. These movements have been described as feeling like a range of things such as butterflies or popcorn popping.\r\n\r\nThis week your partner might notice constipation and varicose veins. Their back may also start to hurt. This is a very common symptom during pregnancy that continues until the baby is born as the growing baby only adds more pressure to the back. Try suggesting the use of a pregnancy pillow. This can really help support your partners back and may help relieve some of their discomfort.\r\n\r\nIf your partner is of a more advanced maternal age the doctor might offer an amniocentesis around this time. This involves medical tests to ensure the baby is healthy or raise concerns if applicable. ', 'Your baby is now 4 and half inches long which is roughly the same size as a pickle, and weighs 4 ounces. Your baby can hear what is happening in the world around us now that the ears have developed more. Even though their eyes remain closed at this stage your child\'s eyes are still developed enough to detect light through their mothers belly.\r\n\r\nYour partner might feel your little one kick soon and these first movements are often known as quickening. If this is your partners first pregnancy they may not feel these movements for another few weeks yet. '),
(17, 0, 'The main pregnancy symptom that your partner might be experiencing at this week is round ligament pain felt in the stomach, uterus and groin area predominantly. \r\nYou can suggest to your partner that she lie on her left side to reduce the amount of stress on the uterus and therefore alleviate some of the pain she might experience. \r\nA maternity belt can also be worn to help reduce the pain and support your partners belly. \r\nYour partners appetite might also pick up soon, as the baby requires more nutrients each day to develop.\r\n\r\nThis stage of the pregnancy might also introduce weird dreams. Your partner may also begin to waken up for bathroom runs, aches and pains during the night. This will only get worse as the third trimester approaches.', 'Your baby this week is 5 inches long which is about the same size as a pomegranate. Your little one\'s bones are now starting to solidify and the umbilical cord is strengthening also with your baby\'s heart beating up to 150 times a minute. Your baby\'s brain is now controlling the heartbeat rather than it beating at random intervals. \r\nAll the other senses are still developing and if your baby is a girl she is already producing millions of eggs in her ovaries that she could use to be a mum someday herself.'),
(18, 0, 'Your partners appetite will have increased in order to facilitate all the fat your little one is beginning to store for warmth. \r\nAnother common symptom is low blood pressure and therefore it is important that your partner doesn\'t rise from sitting or lying down too quickly. Low blood pressure happens quite often due to the circulation system expanding to accommodate the increased blood flow. Low blood pressure peaks half way through the second trimester and then begins to dissipate. Until then advise your partner to slow down and take her time.', 'This week your baby is moving and punching and kicking harder than ever before and your partner may even be able to feel it. \r\nYour baby can now yawn, hiccup and swallow and they are starting to develop a thin layer of fat over their muscles. This will increase until they\'re born.\r\nYour baby is also developing myelin on its nerves which protects and facilitates the brain\'s communication with the nervous system. Myelin is very important your baby\'s brain development. \r\nYour baby at this stage is 5 and half inches long, the same size as a sweet potato and weighs in at roughly 7 ounces.'),
(19, 0, 'Your partner will still be experiencing all the previous symptoms that came along with the second trimester but she might also be noticing red palms or areas of darkened skin. The changes in pigment happen due to the extra estrogen and progesterone in the system during pregnancy. \r\nThese changes to the skin will disappear once your partners hormone levels return to normal. The pigment around her nipples will also darken however this is an evolutionary tactic to make it easier for the baby\'s eyes to find the breast when breastfeeding.\r\n\r\nYour partner might also be experiencing hip pain because the body releases a hormone to relax the muscles in the body which can cause added pressure on the relaxed ligaments. If your partner is experiencing this, suggest the use of a pillow under her hips or putting a pillow between her knees while she sleeps on her left side, as this will reduce the amount of pressure on her hips.\r\nShe may also notice stretch marks starting to appear. If she wants to combat the stretch marks suggest using a fragrance-free moisturizer.', 'Your baby is starting to sprout more little tiny hairs from the top of its little head. Your baby\'s coordination is also developing more and more everyday as neurons make more and more connections with the muscles, giving your little one better control over their arms and legs. \r\nYour baby is now measuring approximately 6 inches long, which is similar to that of a zucchini, and weighs roughly 8 and a half ounces. \r\nYour baby has certainly developed from that little ball of cells it started out as. Before you know it, he or she will be in your arms.'),
(20, 0, 'You and your partner have made it half way through the pregnancy! Your partner will continue to need more iron due to the increased blood flow so suggest that she eats red meats, soy products or raisins.\r\nShe may begin to notice her nails hardening and her hair thickening. This is one side affect of pregnancy that isn\'t bad for a change. \r\nHowever, hair may begin to grow in places your partner isn\'t used to having hair such as the belly or chin. This is completely normal and common, and usually goes back to normal shortly after delivery. A brown line may also appear running down your partners stomach. This is known as linea nigra and is also a common pigment change during pregnancy.\r\n\r\nYour partner may also be finding it harder to sleep at night. She may toss and turn to find a comfortable position. This can be hard due to moving the weight of both her own body and the baby\'s. The expanding uterus may also begin to push up against your partners lungs resulting in a shortness of breath.', 'This week is a milestone for your baby as it has straightened enough now to be measured from head to toe instead of crown to rump length. Due to this your baby is now measuring roughly 10 inches this week, which is roughly the size of an endive, and weighs approximately 10 and a half ounces. If your baby is a girl she now has 7 million primitive eggs in her ovaries, and if it is a boy his testicles are descending from his abdomen into the scrotum\r\n\r\nAt this stage your health care provider will be able to see the presence or lack of genitalia making it possible for you and your partner to find out the sex of your baby if you choose to do so. \r\nYour baby will also get an in-depth check at your 20 week ultrasound appointment to measure many different parts of your little one\'s body. They will check the brain and the ventricles of the heart as well. These measurements also allow doctors to discover any problems there might be with the baby or the pregnancy.\r\n\r\nYour baby is starting to spout teeth buds under its gums as well as developing its lips, eyelashes and eyebrows. Only 20 short weeks left until you meet your little bundle of joy and see its face that it has been working on so hard to develop.'),
(21, 0, 'Your partner is still experiencing those horrible backaches, but if she persists with exercise and drinking plenty of water she can help herself to feel better. \r\nYour partner might be noticing some dental issues such as bleeding or sore gums. This is a normal side affect of pregnancy due to the change in all of her hormones. Suggest that your partner brushes her teeth with a soft bristled brush to help ease the pain of sore, bleeding gums. Your partner is also entitled to free dental treatment while she is pregnant, and continues to be entitled to free dental treatment up until a year after the baby is born.\r\n', 'Your baby is making meconium, the black tarry substance that makes up your little ones first poop. \r\nBaby fat is very important for your baby\'s development as it fuels brain development and helps your baby regulate its own body temperature when it is born.\r\nYour little bundle of joy is now 10 and a half inches long (26.7cm), which is similar in size to a bok choy and weighs almost 350 grams'),
(22, 0, 'Your partners hands and feet may swell up during these months of pregnancy. Wearing maternity compression stockings might help your partners circulation to reduce swelling. You might find that your partner\'s feet can grow up to an entire size bigger. \r\n\r\nHeartburn might be bothering your partner at this stage, and if this is the case your partner can take safe heartburn medication approved by a health care provider. Your partner may also notice that her once inward belly button has become an \'outie\'. This is due to the expanding uterus and will return to normal after delivery. ', 'Your baby sleeps approximately 12-14 hours every day and is actively discovering the ability to touch. Your baby will be touching its face, body and even the umbilical cord. Reaching out for things allows your baby to practice physical ability and motor skills.\r\nYour baby\'s ears have also developed to a point where your baby now has a sense of balance and can probably hear you and your partner too! When your little one arrives they will instantly recognize you.\r\n\r\nYour baby is now creating its own hormones which will help reduce your partners hormonal burden.\r\nYour little bundle of joy is now about a foot tall (30.5cm) and weighs close to a pound now (450g).\r\nYour baby is now the same size as an ear of corn'),
(23, 0, 'Although swelling of extremities is something your partner should be used to by now, excessive swelling could be a symptom of preeclampsia, which is a condition characterized by high blood pressure and protein present in the urine. Preeclampsia can be dangerous if untreated so make sure your partner seeks help from a healthcare provided if swelling seems out of the ordinary or they notice any other symptoms of preeclampsia.\r\n\r\nYour partner might also notice tingling in the hands due to carpal tunnel which has developed during pregnancy. This usually goes away after delivery so a healthcare might do nothing now to treat it however, in some cases they might use a splint.\r\n\r\nOther symptoms your partner might notice include forgetfulness, snoring and braxton hicks contractions. Braxton hicks aren\'t really painful they just prepare the body for birth. Advise your partner to time the contractions and if they aren\'t regular or they go away with movement then these are most likely braxton hicks contractions.\r\n\r\nAt this stage of the pregnancy a healthcare provider will probably test the baby\'s mother for gestational diabetes. This is diabetes that is developed during pregnancy and will usually disappear after delivery. ', 'Your baby\'s skin is still transparent and becoming a bit red as more arteries and veins are developed under the skin. Soon your baby will be packing on the fat eliminating the transparent, red look that is currently visible.\r\nYour baby\'s face is fully formed now and your little one is kicking like crazy, usually in response to sounds or lights occasionally.\r\nYour little one is now approximately 30.5cm tall, similar in size to a bunch of grapes and weighs almost 20 ounces (570g)'),
(24, 0, 'Between linea nigra and stretch marks your partner might be noticing her skin is giving her a lot of trouble. You can advise your partner to use tropical creams and avoid baths that are too long as they will dry the skin out. \r\nYour partners ankles and fingers may be swollen due to fluid retention. Let your partner know that rest and elevating/icing the area can help reduce and alleviate some of the pain and swelling. \r\nYour partner may also be noticing constipation, headaches and dry eyes. These are just more expected joys associated with pregnancy. If your partner hasn\'t already been checked for gestational diabetes, make sure she gets tested in the next couple of weeks.', 'This week your baby has developed taste buds, meaning that soon they will be able to get a stronger taste from the food your partner eats.\r\nAccording to various studies these tastes can impact their food choices later in life.\r\n\r\nYour little one\'s lungs are now significantly developed and are creating a very important substance that will help the lungs expand to keep them from sticking together. Your baby has also gained roughly 110 grams in bones, muscles and fat now, and is beginning to look more like the baby shape we expect to see. Your baby\'s skin is starting to take on more of a pink hue. Your little one is now about 13 inches long, which is similar to the size of an eggplant and weighs 1.5 pounds (680g)');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `pregnancy_by_week`
--
ALTER TABLE `pregnancy_by_week`
  ADD PRIMARY KEY (`id`),
  ADD KEY `user_id` (`user_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `pregnancy_by_week`
--
ALTER TABLE `pregnancy_by_week`
  MODIFY `id` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
